#!/usr/bin/env bash

# This hook ensures lua code is formatted before committing.

# NOTE: Given this is the 'pre-commit' script, hooks will need
# rearranged into their own scripts if another is added.

REPO_ROOT=$(git rev-parse --show-toplevel)
cd $REPO_ROOT

# Exit early if no Lua files are staged
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=d | grep -E "^.*\.lua$")
if [ -z $CHANGED_FILES ]; then
    exit 0
fi

stylua --check . >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Stylua check failed!"
    stylua . >/dev/null 2>&1
    echo ""
    echo "Invalid changes have been auto-formatted. Please stage them and try again."
    exit 1
fi

exit 0
